apiVersion: v1alpha
kind: xcuitest
sauce:
  region: us-west-1
  concurrency: 1
  metadata:
    name: Testing XCUITEST Support
    tags:
      - e2e
      - release team
      - other tag
  build: Release $CI_COMMIT_SHORT_SHA

xcuitest:
  app: ./apps/FormeLife.ipa
  testApp: ./apps/FormeLifeUITests-Runner.ipa

suites:
  - name: "Forme Life Smote XC UI Test"
    testOptions:
      class: ["FormeLifeUITests.SmokeUITests/test6755"]
    devices:
      # If set, only device by ID will be queried.
      #- id: <rdc_device_id>
      - name: "iPhone.*"
        platformVersion: "14.6"
        options:
          # If set, only devices with a SIM card will be queried.
          carrierConnectivity: false
          # Possible values [ANY,PHONE,TABLET]
          deviceType: PHONE
          # If set, only private devices will be queried.
          private: false

artifacts:
  download:
    when: always
    match:
      - "*"
    directory: ./artifacts/
